### ISSUE TITLE
Improve Keypair instanciation

### ISSUE THREAD

**Issue by pakokrew** [stellar/js-stellar-base#101]
Keypair instanciation fails if we pass to the object only the secret seed, although it could deduce public from seed.

For now we must write this kind of code to instanciate : 
```js
  if (keypair.secretSeed) {
    return Keypair.fromSecret(keypair.secretSeed);
  }
  return Keypair.fromPublicKey(keypair.publicKey);
```

Also, it could be nice to have the same name for the getters than for the object properties (now we have `secretSeed` for instanciation and `secret` for the getter)

**Comment by bartekn** [comment]
You can use: 
```js
let keyPair = Keypair.fromSecret(secretSeed);
console.log(keyPair.secret()); // S...
console.log(keyPair.publicKey()); // G...
```
Constructor should be used only with raw keys.

**Comment by pakokrew** [comment]
I think you misunderstood my issue.
On the [reference](https://stellar.github.io/js-stellar-sdk/Keypair.html), when we use `new Keypair(keys)`, the keys object is :

```
publicKey: string
secretSeed: string (optional)
```
The public key is mandatory but secret seed is optional. What I meant is that we could either pass public or seed in props. When we pass seed we don't need to pass public key.

**Comment by pakokrew** [comment]
And the `keypair.secret()` method has a different name from `keys.secretSeed` property.
