### ISSUE TITLE
Keys generation and BIP39

### ISSUE THREAD

**Issue by sonaye** [stellar/js-stellar-base#118]
I am trying to understand the mechanism of keys generation, I am interested in the implementation itself rather than just using the high-level utilities offered, to gain a better understanding of the whole ecosystem and whatnot.

After digging into the source code, I managed to come up with the following lines, which I think are the main components behind the process. However, the output is not right.

I would appreciate it if someone can offer a correction and some technical comments on how this is done exactl.

```javascript
import base32 from 'base32';
import bip39 from 'bip39';
import crc from 'crc';
import nacl from 'tweetnacl';

// is it possible to utilize bip39 to generate the seed?
// const mnemonic = bip39.generateMnemonic();
// const seed = bip39.mnemonicToSeed(mnemonic); // error: invalid seed size

const seed = nacl.randomBytes(32);

const secretKey = new Buffer(seed.secretKey);
const publicKey = new Buffer(seed.publicKey);

// what are we doing here exactly?
const version = new Buffer([6 << 3]); // 18 << 3 for secret
const payload = Buffer.concat([version, publicKey]);

// what are we doing here too?
const checksum = new Buffer(2);
checksum.writeUInt16LE(crc.crc16xmodem(payload), 0);

const raw = Buffer.concat([payload, checksum]);

base32.encode(raw); // dumps an invalid wallet address, something is not right above
```

**Comment by bartekn** [comment]
Check [SEP-0005](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0005.md) for key derivation in Stellar.

**Comment by sonaye** [comment]
@bartekn The document was very helpful. I am trying to understand how you translated all of that and built it within the SDK itself though, the technical implementation via code.

Every single reference I found utilizes the base SDK for key derivation, I want to understand how can this be achieved without it, or in other words: how to build it from scratch.

The code I referenced above is taken from the SDK itself ([keypair.js](https://github.com/stellar/js-stellar-base/blob/master/src/keypair.js) and [strkey.js](https://github.com/stellar/js-stellar-base/blob/master/src/strkey.js)), I am not getting the same results however, which means that the code is broken somewhere. Kindly advise on this.

**Comment by sonaye** [comment]
Literarily copy paste from the sdk, yet a different result.

```javascript
import base32 from 'base32';
import crc from 'crc';
import nacl from 'tweetnacl';

createAccount = () => {
  // from keypair/random
  let secret = nacl.randomBytes(32);

  // from keypair/constructor
  secret = new Buffer(secret);

  secret = new Uint8Array(secret);
  secret = nacl.sign.keyPair.fromSeed(secret);

  let key = new Buffer(secret.secretKey);

  // from keypair/publicKey
  // from strkey/encodeEd25519PublicKey
  // from strkey/encodeCheck
  key = new Buffer(key);
  const version = new Buffer([18 << 3]);
  const payload = Buffer.concat([version, key]);

  // from strkey/calculateChecksum
  const checksum = new Buffer(2);
  checksum.writeUInt16LE(crc.crc16xmodem(payload), 0);

  const unencoded = Buffer.concat([payload, checksum]);

  const addr = base32.encode(unencoded);

  console.log(addr);
  // j1nrnwkge7m3cray5xjpz1ydvv22ttgd0kqze6dxp37cm6kzqxgcg1ujtwm1bxdygvqwk7xm9z3m0br4bumtm7jwyk5hkvrve842put245wg
};
```

**Comment by sonaye** [comment]
Same thing with BIP39. I am doing something terribly wrong after obtaining the key pair for sure.

```javascript
import bip39 from 'bip39';
import nacl from 'tweetnacl';
import { derivePath } from 'ed25519-hd-key';

createWallet = () => {
  let secret = bip39.generateMnemonic();
  secret = bip39.mnemonicToSeedHex(secret);
  secret = derivePath("m/44'/148'/0'", secret).key;
  secret = nacl.sign.keyPair.fromSeed(secret);

  const key = new Buffer(secret.secretKey);

  console.log(key);
};
```

**Comment by bartekn** [comment]
There's already a JS implementation here: https://github.com/chatch/stellar-hd-wallet I haven't checked the code yet so I can't confirm it's 100% correct and secure but it passed the tests from SEP-0005.

**Comment by sonaye** [comment]
That implementation is based on the Stellar SDK, which is not what I am looking for.

I managed to get it to work, detailed [here](https://github.com/sonaye/lumens/blob/master/test/src/lumens/index.js) and an example is available [here](https://github.com/sonaye/lumens/blob/master/test/src/index.js). 

I was able to extract all the methods I need to get Stellar working with React. I can create a Lumens deterministic wallet, check its balance, get its transactions history, all without needing the Stellar SDK, because it doesn't work with React.

One method is left, the most important one actually, which is building a transaction. I took a look at the transaction builder [source code](https://github.com/stellar/js-stellar-base/blob/master/src/transaction_builder.js) and oh boy .. this one is tough to reverse engineer, it also depends heavily on the package that breaks React in the first place `js-xdr`, see https://github.com/stellar/js-stellar-sdk/issues/88.

Do you have any suggestion on how can I approach this?

**Comment by sonaye** [comment]
Related issues:
https://github.com/stellar/js-stellar-sdk/issues/126
https://github.com/stellar/js-stellar-sdk/issues/127
