### ISSUE TITLE
Add TypeScript definitions to DefinitelyTyped

### ISSUE THREAD

**Issue by danrobinson** [stellar/js-stellar-base#140]
Now that the full Stellar SDK has [TypeScript type definitions](https://www.npmjs.com/package/@types/stellar-sdk), it would be nice to backport some of those to this project as well, so projects that aren't using the full SDK can take advantage of them.

I'm happy to take the initiative on this if it sounds like a reasonable idea.

**Comment by bartekn** [comment]
Sounds good to me!

**Comment by Akuukis** [comment]
PR is up - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32025

**Comment by Akuukis** [comment]
PR merged.

**Comment by morleyzhi** [comment]
Seems like this is fixed now.
