### ISSUE TITLE
Extremely small trades appear to succeed when they've failed 

### ISSUE THREAD

**Issue by vcarl** [stellar/js-stellar-base#148]
Continuing a conversation from stellar/stellar-protocol#195, extremely small trades (e.g. 0.0000001 XLM) appear to submit successfully, but actually are never placed on the orderbook. 

Per [this comment](https://github.com/stellar/stellar-protocol/issues/195#issuecomment-434828234) it seems that it should be possible to determine when this has happened from the returned XDR, but that seems awfully close to the protocol for a web app to be dealing with. 

I believe it would be more appropriate for SDK itself (or Horizon, alternatively) to return an error in this circumstance.

**Comment by bartekn** [comment]
Duplicate https://github.com/stellar/js-stellar-sdk/issues/209.
