### ISSUE TITLE
inconsistent type of Memo<'text'>.value

### ISSUE THREAD

**Issue by Akuukis** [stellar/js-stellar-base#152]
`Memo` of type `text` may have value either as `string` of `Buffer`. Looks inconsistent to me, I'd expect always to have one type. Is this a bug or intended?

```ts
import * as sdk from 'stellar-sdk'

const memo = sdk.Memo.text('thisIsTypeOfString')
console.log(typeof memo.value === 'string', memo)  // string here

var xdr = new sdk.TransactionBuilder(new sdk.Account('GC46O6E46V6UBEE3KLQWHPJX5QBO2QHZRGJC2OFGO3WVXFKJ7K4MU73L', '1234'))
    .addOperation(sdk.Operation.manageData({ name: `foo`, value: 'bar' }))
    .addMemo(memo)
    .build()
    .toEnvelope()
    .toXDR()
    .toString('base64')

var memo2 = new sdk.Transaction(xdr).memo
console.log(memo2.value instanceof Buffer, memo2)  // Buffer here
```

**Comment by bartekn** [comment]
It is intended and this change was made recently in https://github.com/stellar/js-stellar-base/pull/142. JS SDK support strings only as when setting value of `memo_text`, however stellar-core does not check encoding of provided bytes. So this is possible that `memo_text` of existing transaction is actually invalid utf8 string.

Changing this would make things like: https://github.com/stellar/js-stellar-sdk/issues/196 possible again.

**Comment by Akuukis** [comment]
@bartekn understood on why that can't be a string in both cases. So let's make it as Buffer in both cases for consistency?
