### ISSUE TITLE
Improve setTimeout documentation

### ISSUE THREAD

**Issue by morleyzhi** [stellar/js-stellar-base#155]
The docs say that setTimeout takes an argument of type "timeout" when it's actually an integer of the number of ~milliseconds~ seconds to wait (I think). This should be clarified.

**Comment by bartekn** [comment]
Isn't this clear: https://github.com/stellar/js-stellar-base/blob/c78dfe1d6e9aefc8e821b82e7676beabd37e0d97/src/transaction_builder.js#L112

**Comment by morleyzhi** [comment]
The value in brackets is supposed to indicate the type - `number`, `string`, etc. I think it would be clearer if the type were "number" instead of "timeout". The description also references implementation details like `minTime` and `maxTime` that aren't part of the function's interface, but could confuse people to think that they are. (When I first looked at the docs, I first thought that you had to pass `{ minTime, maxTime }`). I'll take a pass to make it clearer what the interface is and what the function is doing.
