### ISSUE TITLE
Operation base fee should be dynamic

### ISSUE THREAD

**Issue by tomerweller** [stellar/js-stellar-base#165]
Currently, base fee is hard-coded in the transaction builder: 
https://github.com/stellar/js-stellar-base/blob/master/src/transaction_builder.js#L10

However, base fee can *and will* change and the SDKs should be prepared. 

You can always get the latest base fee from the latest ledger resource. We need to decide on whether to do this in behalf of the user (or maybe it belongs in the js-stellar-sdk layer?) and if so, how often. Every time a transaction is built? Every specific interval?

**Comment by morleyzhi** [comment]
Dumping some thoughts here for everyone's comment.

Given @bartekn's points about this library not connecting to Horizon, and given that TransactionBuilder has support for custom fees, I think custom fee calculation should be performed in `stellar-sdk`, probably through a helper function. Maybe it would look like this:

```javascript
import { TransactionBuilder, fetchFee } from 'stellar-sdk';

const transaction = new TransactionBuilder(account, {
  fee: await fetchFee()
})
  .addOperation(operation)
  .setTimeout(30)
  .build();
```

Maybe we expose different fee-calculating strategies (though I don't recommend that; I think we should avoid choice paralysis and choose the best option for most cases):

```
import { fetchFee, fetchMedianFee, fetchGuaranteedTransactionFee } from "stellar-sdk";
```

**Comment by tomerweller** [comment]
@morleyzhi good point about horizon and I like this style. 

Do you think it makes sense that the `TransactionBuilder` has a default base fee at all? I'm thinking we should deprecate it and require consumers to input fees, essentially forcing them to use one of your suggested helper functions.

**Comment by morleyzhi** [comment]
Yeah, that's a good idea. In that vein, the next breaking-change revision of this library should issue a warning in development when the `fee` property is not provided, so that later we can turn the warning into an error.

**Comment by tomerweller** [comment]
Closing in favor of https://github.com/stellar/js-stellar-base/issues/166 and https://github.com/stellar/js-stellar-sdk/issues/233
