### ISSUE TITLE
OperationResult has no method 'read'

### ISSUE THREAD

**Issue by thejollyrogers** [stellar/js-stellar-base#2]
this is the same section of code we were looking at earlier
//aSwitch =
{ name: 'txFailed', value: -2 }
// arm =
arm: results
// armType = 
{ _childType: 
   { [Function: ChildUnion]
     unionName: 'OperationResult',
     _switchOn: 
      { [Function: ChildEnum]
        enumName: 'OperationResultCode',
        _members: [Object],
        _byValue: {},
        opInner: [Function],
        opBadAuth: [Function],
        opNoAccount: [Function] },
     _switches: {},
     _arms: { tr: [Object] },
     opInner: [Function],
     opBadAuth: [Function],
     opNoAccount: [Function] },
  _maxLength: 2147483647 }
TypeError: Object [object Object] has no method 'read'
    at Function.read (/Users/andrewrogers/Code/stellar/js-stellar-lib/node_modules/stellar-base/node_modules/js-xdr/lib/union.js:109:29)

The XDR in question looks like:

  xdr.union("TransactionResultResult", {
    switchOn: xdr.lookup("TransactionResultCode"),
    switchName: "code",
    switches: {
      txSuccess: "results",
      txFailed: "results" },
    arms: {
      results: xdr.varArray(xdr.lookup("OperationResult"), 2147483647) },
    defaultArm: xdr["void"]() });

**Comment by nullstyle** [comment]
Please paste the hex-encoded XDR you were trying to decode.

**Comment by thejollyrogers** [comment]
000000000000001e0000000000000003000000000000000000000000000000000000000300000000000000000000000000000000

**Comment by thejollyrogers** [comment]
or 000000000000001efffffffe00000003000000000000000000000000000000000000000300000000fffffffe

**Comment by thejollyrogers** [comment]
and another one 
00000000000000140000000000000002000000000000000000000000000000000000000300000000

**Comment by nullstyle** [comment]
Fixed in https://github.com/stellar/js-xdr/commit/090e1b6870b0608d45f93c6137919dac898cec43

Please report back and close the issue if it is fixed for you.
