### ISSUE TITLE
Add js-stellar-base to cdnjs.com

### ISSUE THREAD

**Issue by irisli** [stellar/js-stellar-base#20]
https://cdnjs.com/about

This will make it easier to get people quickly started in the browser. To tinker around, all they have to do is include an already hosted script from cdnjs.

**Comment by bartekn** [comment]
:+1: I think it will be very helpful.

**Comment by cyberomin** [comment]
Hey @irisli & @bartekn I created an issue on the CDN-JS issue page for this particular issue - https://github.com/cdnjs/cdnjs/issues/6979

**Comment by bartekn** [comment]
Thanks @cyberomin. We should do the same with js-stellar-sdk (https://github.com/stellar/js-stellar-sdk/issues/57). Do you want to do it?

**Comment by cyberomin** [comment]
Hey @bartekn, I have submitted an issue for it. It should be added pretty soon. Here is the link to the issue - https://github.com/cdnjs/cdnjs/issues/6986

**Comment by PeterDaveHello** [comment]
Added in https://github.com/cdnjs/cdnjs/commit/a3924ed940717eba14f5e251a35bd3bc434d87e4

**Comment by PeterDaveHello** [comment]
Guys would you like to add a link to cdnjs on this project? So that the users will know they can use the CDN :smile:

**Comment by irisli** [comment]
Thanks for adding the issue @cyberomin. 

Thank you @PeterDaveHello for adding it in cdnjs and maintaining cdnjs. I've added instructions to the README.md on how to use the script f rom cdnjs.

**Comment by PeterDaveHello** [comment]
Nice @irisli
