### ISSUE TITLE
Missing type for TransactionBuilder.TransactionBuilderOptions.networkPassphrase

### ISSUE THREAD

**Issue by mragiadakos** [stellar/js-stellar-base#237]
**Describe the bug**
Using typescript with the latest version of stellar-sdk, I can not disable a message, because it does not compile the attribute 'networkPassphrase'

This is the message
> Global class `Network` is deprecated. Please pass explicit argument instead, e.g. `new Transaction(envelope, Networks.PUBLIC)` (see https://git.io/fj9fG for more info).

**What version are you on?**
Running stellar-base v1.1.0 

**To Reproduce**
Try an example that uses TransactionBuilder in Typescript with the attribute networkPassphrase to Networks.TESTNET and try to compile it

**Expected behavior**
It will not compile.

**Comment by abuiles** [comment]
@mragiadakos thanks for the report! We'll push a new release soon to fix this.

**Comment by abuiles** [comment]
@mgreville a fix for this has been merged and is now available in 1.1.1
