### ISSUE TITLE
In manageBuyOffer operation, Can we set a parameter of source?

### ISSUE THREAD

**Issue by park2h83** [stellar/js-stellar-base#269]
**Describe the bug**
In manageBuyOffer operation, we can't set 'source' parameter.
However in api docs(https://stellar.github.io/js-stellar-sdk/Operation.html#.manageBuyOffer), it says we can set. 

**What version are you on?**
stellar-sdk : 3.0.0

**Additional context**
In  stellar-base > types > index.d.ts

interface BaseOptions {
    **source**?: string;
  }

  interface CreatePassiveSellOffer extends **BaseOptions** {
    selling: Asset;
    buying: Asset;
    amount: string;
    price: number | string | object /* bignumber.js */;
  }

  interface ManageSellOffer extends **CreatePassiveSellOffer** {
    offerId?: number | string;
  }

**In this interface, there is no 'source' parameter.**

interface ManageBuyOffer {
    selling: Asset;
    buying: Asset;
    buyAmount: string;
    price: number | string | object /* bignumber.js */;
    offerId?: number | string;
  }

**Comment by NovichikhinAlexey** [comment]
Look like error here:
https://github.com/stellar/js-stellar-base/pull/270/files

Guys please check this and update library asap if this is right and if it possible

**Comment by abuiles** [comment]
@NovichikhinAlexey thanks for the PR! I just released stellar-base@2.0.2 which should address this issue
