### ISSUE TITLE
cannot set trust with limits

### ISSUE THREAD

**Issue by FredericHeem** [stellar/js-stellar-base#28]
See https://github.com/FredericHeem/js-stellar-base/commit/80811950f4b50642d162014533e1a0f46b9775fc#diff-651338dca488e1563dbd60ce4cfd9fe8R172

**Comment by bartekn** [comment]
Fixed in @31c690eab05b63b94ce9bf279c3c420da3b9c7d1.

**Comment by FredericHeem** [comment]
and the unit test ?
