### ISSUE TITLE
Missing TypeScript toXDR property declaration on the Transaction class

### ISSUE THREAD

**Issue by tyvdh** [stellar/js-stellar-base#295]
**Describe the bug**
Transaction class is missing toXDR type property declaration.

![Screen Shot 2020-01-31 at 2 41 00 PM](https://user-images.githubusercontent.com/4383610/73570884-4df6ca80-443b-11ea-854e-a31946ad27f2.png)

**What version are you on?**
"stellar-sdk": "^3.3.0"

**To Reproduce**
const transaction = new Transaction(xdr, networkPassphrase)
transaction.sign(keypair)
transaction.toXDR()

**Comment by abuiles** [comment]
Fixed by #296
