### ISSUE TITLE
TS Errors trying to build envelope from xdr string

### ISSUE THREAD

**Issue by msfeldstein** [stellar/js-stellar-base#306]
**Describe the bug**
I have a base64 encoded xdr string representing a TransactionEnvelope.  I'd like to instantiate a TransactionEnvelope object using 
```const envelope = xdr.TransactionEnvelope.fromXDR(tx, "base64")```
where `tx` is a base64 encoded string.  The typescript error detection marks this as an error 
```Expected 1 arguments, but got 2.```
when trying to pass the `"base64"` string.  Without passing that string, it can't properly decode the xdr.

The error not only causes red errors in the editor, but also causes some build tools, such as stencil to fail.

**What version are you on?**
2.1.6

**To Reproduce**
Run the above line of code in a typescript aware editor like vscode.  

**Expected behavior**
There should be no error, code should compile correctly

**Comment by msfeldstein** [comment]
![Screenshot 2020-02-26 at 12 59 04 PM](https://user-images.githubusercontent.com/161135/75388162-59ea7680-5899-11ea-8f9d-0dadef275996.png)

<img width="654" alt="Screenshot 2020-02-26 at 1 10 27 PM" src="https://user-images.githubusercontent.com/161135/75388179-6078ee00-5899-11ea-8523-8081fe2a6016.png">

**Comment by abuiles** [comment]
@msfeldstein interesting! can you update the definition here ? https://github.com/stellar/js-stellar-base/blob/master/types/index.d.ts#L582 that must be it

**Comment by msfeldstein** [comment]
sure, that definition is not auto-generated right?

**Comment by abuiles** [comment]
@msfeldstein in the latest version of this library, you can do `TransactionBuilder.fromXDR` and pass a string.

Also I'm working on auto-generated TS definitions, if you want to test it out, install `    "stellar-base": "3.0.1-beta.1"` and do `import { xdr } from 'stellar-base'`
