### ISSUE TITLE
Can't delete a data entry

### ISSUE THREAD

**Issue by park2h83** [stellar/js-stellar-base#309]
**Describe the bug**
I can't delete a data entry that is attached to a particular account by using js-stellar-sdk.

**What version are you on?**
js-stellar-base : 2.1.6
js-stellar-sdk : 4.0.2

**Additional context**
See [ js-stellar-base > types > index.d.ts (264 ~ 267 line) ]

To delete a data entry that is attached to a particular account, a 'value' of the interface ManageData must be set 'null'. However we can't do that because of the type.

     interface ManageData extends BaseOptions {
         name: string;
         value: string | Buffer;
      }

If this code change like below, we can set the value to null and delete a data entry.

     interface ManageData extends BaseOptions {
         name: string;
         value: string | Buffer | null;
      }

**Comment by abuiles** [comment]
Fixed in #310
