### ISSUE TITLE
TransactionBuilder.setTimeout(0) makes .build() fail

### ISSUE THREAD

**Issue by johansten** [stellar/js-stellar-base#312]
**Describe the bug**
TransactionBuilder.setTimeout(0) doesn't work, and leads to an error at L221, where this.timebounds.maxTime can't be converted to a string because it perhaps doesn't exist?

**What version are you on?**
2.1.6

**To Reproduce**
create a builder
add your operations to it
call setTimeout(0)
call .build()

**Expected behavior**

I'd expect build() to succeed.

**Additional context**
[...]/node_modules/stellar-base/lib/transaction_builder.js:257
        this.timebounds.maxTime = _jsXdr.UnsignedHyper.fromString(this.timebounds.maxTime.toString());
                                                                                          ^

TypeError: Cannot read property 'toString' of undefined
    at TransactionBuilder.build ([...]/node_modules/stellar-base/lib/transaction_builder.js:257:91)

**Comment by abuiles** [comment]
@johansten can you include a gist/replit that shows this issue? I tried to reproduce but it didn't fail https://repl.it/repls/SoftStripedTwintext 

Also, this might be related - https://github.com/stellar/js-stellar-base/pull/303 -- I'll cut a release soon with the fix.

**Comment by abuiles** [comment]
@johansten this has been fixed and it's available in 2.1.8
