### ISSUE TITLE
Add a function to decode TransactionResultPair

### ISSUE THREAD

**Issue by FredericHeem** [stellar/js-stellar-base#32]
On the browser, the *Buffer* object is not implemented, therefore the following code to decode a TransactionResultPair fails:

    xdr.TransactionResultPair.fromXDR(new Buffer(result_xdr, "base64"));

The workaround is to encapsulate it inside a function within the *js-stellar-base* which contains a local implementation of *Buffer*

See implementation at https://github.com/stellar/js-stellar-base/pull/19/files#diff-42d8d2088a96641b563b25ad908b0c0fR94

**Comment by bartekn** [comment]
This problem affects other XDR structures as well. I think it's better to add a helper method (`fromBase64XDR`?) in `js-xdr`.

**Comment by nullstyle** [comment]
Personally, I would prefer we add an optional, second parameter to `fromXDR` that mirrors the second parameter to `Buffer`'s constructor.

```js
// decodes the buffer directly
xdr.TransactionResultPair.fromXDR(aBuffer)

// decode the buffer after first decoding from hex
xdr.TransactionResultPair.fromXDR(aBuffer, 'hex')

// decode the buffer after first decoding from base64
xdr.TransactionResultPair.fromXDR(aBuffer, 'base64')
```
