### ISSUE TITLE
Return V1 TransactionEnvelopes in `txbuilder.build()` after protocol 13 is released.

### ISSUE THREAD

**Issue by abuiles** [stellar/js-stellar-base#322]

**Comment by MisterTicot** [comment]
Are hardware wallets ready to handle those? Else, it may be better to use V1 envelopes only when protocol 13 features are being used.

**Comment by abuiles** [comment]
@MisterTicot good point! I don't think they handle v1 yet,  we'd need to wait until they add support for it.
