### ISSUE TITLE
Check to see if keyword arguments are legitimate

### ISSUE THREAD

**Issue by dydt** [stellar/js-stellar-base#35]
It's possible to pass in options that are not valid without any errors.  For example, `setOptions` (https://github.com/stellar/js-stellar-base/blob/master/src/operation.js#L213) does not take a `thresholds` object (even though the comments indicate that it does).  Passing a `thresholds` object like so:

```
        var transaction = new StellarSdk.TransactionBuilder(account)
            // this operation funds the new account with XLM
            .addOperation(StellarSdk.Operation.setOptions({
                thresholds: {
                    weight: 1, // master key weight
                    low: 1,
                    medium: 2, // a payment is medium threshold
                    high: 2 // make sure to have enough weight to add up to the high threshold!
                }
            }))
            .build();
```
will fail silently.

**Comment by bartekn** [comment]
Arguments for `setOptions` changed in https://github.com/stellar/js-stellar-base/commit/6c3ffa61279c5d8991a1fd04f6ed00409139bfae. I will update js doc and add arguments checks shortly.
