### ISSUE TITLE
[regression] `setTimeout()` reset `timeBounds.minTime`

### ISSUE THREAD

**Issue by MisterTicot** [stellar/js-stellar-base#351]
**Describe the bug**
Since I switched to stellar-sdk 5.x, `setTimeout()` reset minTime to 0

**What version are you on?**
stellar-sdk 5.0.2, stellar-base 3.0.2

**To Reproduce**
Generate Transaction with minTime set, then set a timeout and build. The bug appears both with infinite timeout (maxTime=0) and arbitrary timeout (maxTime=number).

**Comment by abuiles** [comment]
@MisterTicot how are you creating the transaction? I'm a bit confused, by looking at the code, it looks like `minTime` won't be changed - unless you are calling `setTimeout` without any params or without any previous timebounds

**Comment by MisterTicot** [comment]
My mistake, this only happens with `TimeoutInfinite` or timeout=0.

```js
const { Keypair, Account, TransactionBuilder, TimeoutInfinite } = require("stellar-sdk")

const keypair = Keypair.random()
const account = new Account(keypair.publicKey(), "0")
const txb = new TransactionBuilder(account,  {
  fee: 100,
  timebounds: { minTime: 123456789 }
})
txb.setTimeout(TimeoutInfinite)
console.log(txb)
```

**Comment by Shaptic** [comment]
This is closed by the new precondition builder interface
