### ISSUE TITLE
Offer operations don't allow for every JavaScript number to be stated as price

### ISSUE THREAD

**Issue by TorstenStueber** [stellar/js-stellar-base#353]
**Describe the bug**
The API specifications for [manageBuyOffer](https://stellar.github.io/js-stellar-sdk/Operation.html#.manageBuyOffer) and [manageSellOffer](https://stellar.github.io/js-stellar-sdk/Operation.html#.manageSellOffer) state that `price` can be of type `number`. However, internally the number is converted to `BigNumber`, which does not allow for every possible JavaScript number as an argument and throws an error. One example is the value `1/389.99954`, which yields the error message

`BigNumber Error: new BigNumber() number type has more than 15 significant digits: 0.0025641055884322323`

**What version are you on?**
3.0.3

**To Reproduce**
Create a `manageBuyOffer` operation with `price: 1/389.99954`.

**Expected behavior**
No error thrown.

**Comment by itdsntwork** [comment]
This happens because of the version of the bignumber.js library version.
To resolve this we should either upgrade the version if possible or instantiate big number by adding `toString` eg 
`new BigNumber(number.toString())`

**Comment by Shaptic** [comment]
Creating an operation w/ this price appears to no longer throw
