### ISSUE TITLE
Settings memo for the tx builder seems to fail

### ISSUE THREAD

**Issue by buhrmi** [stellar/js-stellar-base#37]
Tried setting a memo for a tx in multiple ways, but it always throws an exception when building it.

Things I tried
b = new StellarBase.TransactionBuilder(id, memo: 'hello)
b = new StellarBase.TransactionBuilder(id, memo: (StellarBase.Memo.text('hello))
b.memo = 'hello'
b.memo = StellarBase.Memo.text('hello')

**Comment by bartekn** [comment]
It should be:
```js
var tx = new StellarBase.TransactionBuilder(source, {memo: StellarBase.Memo.text('Hello!')})
// ...
```
But I will push `addMemo` helper method shortly:
```js
var tx = new StellarBase.TransactionBuilder(source)
   .addMemo(StellarBase.Memo.text('Hello!'))
// ...
```
