### ISSUE TITLE
Missing Keypair.fromRawEd25519PublicKey function

### ISSUE THREAD

**Issue by movitto** [stellar/js-stellar-base#383]
**Is your feature request related to a problem? Please describe.**

The following converts ed25519 keys exposed in transactions retrieved from horizon to the common address format using python:

```
from stellar_sdk.keypair import Keypair
from stellar_sdk.xdr.curve25519_public import Curve25519Public

xdr = "bG6V1yJrZZ7OWLBBaL3UYQ0ufp/jfQt49fLNsjX2b+Q="
curve_public = Curve25519Public.from_xdr(xdr)
keypair = Keypair.from_raw_ed25519_public_key(curve_public.key)
print(keypair.public_key) # GBWG5FOXEJVWLHWOLCYEC2F52RQQ2LT6T7RX2C3Y6XZM3MRV6ZX6IJHP
```

While various functions such as **fromRawEd25519Seed** and **fromPublicKey** can be found in both the javascript and stellar API, no **fromRawEd25519PublicKey** functions exists.

**Describe the solution you'd like**
We are looking for this function to be exposed so that ed25519 keys can be converted to the common address format.

**Describe alternatives you've considered**
Various attempts have been made using the javascript stellar-sdk function calls, see this galactictalk [topic](https://galactictalk.org/d/2563-xdr-format-details-documentation/8) for more info

**Additional context**
N/A

**Comment by overcat** [comment]
You can implement it like this in the JS SDK.
```js
const StellarBase = require("stellar-base")

const xdr = "bG6V1yJrZZ7OWLBBaL3UYQ0ufp/jfQt49fLNsjX2b+Q="
const keypair = new StellarBase.Keypair({type: "ed25519", publicKey: Buffer.from(xdr, 'base64')})
console.log("Public Key: ", keypair.publicKey())
```

**Comment by movitto** [comment]
Thank you greatly @overcat!
