### ISSUE TITLE
Allow creating transactions without timebounds.

### ISSUE THREAD

**Issue by Shaptic** [stellar/js-stellar-base#438]
**Is your feature request related to a problem? Please describe.**
Creating a transaction with no timebounds set is not possible. This is [technically allowed](https://github.com/stellar/stellar-core/blob/master/src/xdr/Stellar-transaction.x#L587) by the XDR, and it would be nice if this was possible in the JS SDK.

Note the distinction between *no timebound at all* and an *empty timebound* (via `setTimeout(InfiniteTimeout)`). **We heavily discourage both** (see the [docs](https://developers.stellar.org/docs/glossary/transactions/#time-bounds)), but it should be possible for the sake of completeness.

**Describe the solution you'd like**
We can extend `TransactionBuilder.setTimeout` to accept `null` as a value alongside an explicit `iKnowWhatImDoing: true` parameter (name TBD) to avoid setting `tx.timebounds` in the XDR entirely.

**Describe alternatives you've considered**
We could just... not support this (given how heavily we discourage omitting timebounds, having two ways to do so seems odd), but it can be included for the sake of completeness.

**Additional context**
Related is stellar/laboratory#541.

**Comment by leighmcculloch** [comment]
> it would be nice if this was possible in the JS SDK.

Could you elaborate to the use case and who the target audience of this feature is?

---

> not support this (given how heavily we discourage omitting timebounds, having two ways to do so seems odd)

+1 I don't think we should support this in the JS SDK in its helper functions. I doubt that we can maintain supporting a philosophy that all valid XDR should be buildable via the SDKs. If [CAP-21] is accepted there will be four ways to set no time bounds on a transaction and it will make the SDK confusing if we continue that philosophy to there must be a way of using all four ways.

---

Is there a way for a developer to build a transaction using the js-stellar-base and the XDR types within it, without using the higher level types that SDK provides?

**Comment by Shaptic** [comment]
Closing because there's no meaningful reason to encourage / allow empty timebounds. For the hyper-curious, it can still be done by constructing the XDR directly.
