### ISSUE TITLE
don't need TransactionBuilder.addSigner()

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/js-stellar-base#46]
We should just use Transaction.sign()
Build the tx first and then sign it how you need to. We don't need two ways to sign.

**Comment by bartekn** [comment]
Added `@deprecated` flag: https://stellar.github.io/js-stellar-base/TransactionBuilder.html#addSigner Method will be removed in the next major release.

**Comment by bartekn** [comment]
Method removed.
