### ISSUE TITLE
`TransactionBuilder.fromXDR()` does not support muxed accounts

### ISSUE THREAD

**Issue by JakeUrban** [stellar/js-stellar-base#471]
**Describe the bug**

We missed adding the `withMuxing` argument to the follow call ([#L391](https://github.com/stellar/js-stellar-base/blob/master/src/transaction_builder.js#L391)):
```
return new Transaction(envelope, networkPassphrase);
```

We likely need to use the `TransactionBuilder.supportMuxedAccounts` attribute defined in the object's initialization:
```
return new Transaction(envelope, networkPassphrase, this.supportMuxedAccounts);
```

**What version are you on?**

6.0.3

**Comment by Shaptic** [comment]
I believe this is closed by #470 and v6.0.4.
