### ISSUE TITLE
`StrKey.isValidMed25519PublicKey` is not exposed in `types/index.d.ts`

### ISSUE THREAD

**Issue by JakeUrban** [stellar/js-stellar-base#472]
**Describe the bug**

`StrKey.isValidMed25519PublicKey` is not exposed in `types/index.d.ts`, see the [function definition](https://github.com/stellar/js-stellar-base/blob/master/src/strkey.js#L106) and [types declaration](https://github.com/stellar/js-stellar-base/blob/master/types/index.d.ts#L843).

**What version are you on?**

6.0.3

**Comment by Shaptic** [comment]
Closed by #483.
