### ISSUE TITLE
"Uncaught SyntaxError: Unexpected token ILLEGAL" in minified script

### ISSUE THREAD

**Issue by bartekn** [stellar/js-stellar-base#5]
Chrome 43.0.2357.81

**Comment by johansten** [comment]
I'm getting this again, in Chrome 48.0.2564.82.

**Comment by bartekn** [comment]
Is this file part of your build or the problem is with builds here: https://github.com/stellar/bower-js-stellar-base ?

If the former, you may need to add `ascii_only` option to uglify config.
