### ISSUE TITLE
Allow js Date object to be passed to TransactionBuilder to set the TimeBounds

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/js-stellar-base#50]
"TimeBounds is implemented in js-stellar-base in TransactionBuilder.
As a sidenote, I think we can improve it and allow passing js Date object as an argument (right it's only possible to pass uint64 timestamp)."

**Comment by bartekn** [comment]
+ Write tests.

**Comment by Vladeeeeeeeee** [comment]
Free data
