### ISSUE TITLE
Missing XDR definition (Flow control)

### ISSUE THREAD

**Issue by pieterjan84** [stellar/js-stellar-base#506]
Hi, 

Stellar core uses a new overlay xdr message ([SEND_MORE](https://github.com/stellar/stellar-core/blob/a4bcabba04bbf5056f5f20298a5d5b047295af38/src/xdr/Stellar-overlay.x#L103)) to enable flow control between nodes. This xdr definition is not yet included in js-stellar-base. 

Stellarbeat uses the xdr definitions in this package to connect to stellar nodes through [javascript](https://github.com/stellarbeat/js-stellar-node-connector). It needs the SEND_MORE message to be able to connect with nodes when the network upgrades to protocol 19. Protocol 19 will make flow control mandatory. 

Are you planning an update to the xdr definitions? Thanks!

**Comment by Shaptic** [comment]
This will be closed when the [`protocol-19` branch](https://github.com/stellar/js-stellar-base/tree/protocol-19) merges into master! :+1:

**Comment by Shaptic** [comment]
Closed in #521!
