### ISSUE TITLE
Update dependencies for a modern SDK

### ISSUE THREAD

**Issue by BenRacicot** [stellar/js-stellar-base#532]
After digging into the SDK and the API I've noticed several issues and some true roadblocks for front-end web applications.

1. Webpack 5:
The SDK currently uses Webpack 4.33.0. This is a roadblock for all modern apps and frameworks (WP 5 environments)
2. TypeScript 4.5+: 
TypeScript 3.4.5 is outdated and an optimized TS developer experience is _healthy, safer and easier_ for everyone.
3. Fallbacks, updates or recommendations: 
Eventsource and Webpack 4 is a roadblock [[732](https://github.com/stellar/js-stellar-sdk/issues/732)] in a Webpack 5 world. Itself and its deps must be polyfilled. 
This is a compounded issue because the SDK's version 1.0.7 (> 4 years old) would likely require polys that match this version.
4. BigNumber: Just spent an hour debugging `rt.times(...).greaterThan is not a function` which was fixed by falling back to `"bignumber.js": "7.2.1"` from `9.0.2`

**Comment by BenRacicot** [comment]
I finally got Angular polly'd to get the SDK operational. I'm very surprised at how stale this technology is. 
Perhaps @Shaptic would be willing to discuss this in depth? I'm doing something pretty cool at wallethack.com.

Really hope this issue gets the attention it needs from leads at SDF.

**Comment by Shaptic** [comment]
I'm going to close this issue as closed in v9.0.0-beta. Please reopen (or, better yet, comment on #584) if there is more you'd like to see.
