### ISSUE TITLE
Change maximum length of Memo.text to 28

### ISSUE THREAD

**Issue by bartekn** [stellar/js-stellar-base#55]
https://github.com/stellar/stellar-core/blob/4b28573fc59191ec93e76017058834fb917db7c1/src/xdr/Stellar-transaction.x#L256

**Comment by HongxuChen** [comment]
Hi @bartekn , I'm wondering what does "28" mean for unicode characters. Should `价值交易的开源协议!!` (whose length is 29 as reported by `text.getBytes((StandardCharsets.UTF_8)).length` in [java-stellar-base](https://github.com/stellar/java-stellar-base/blob/master/src/main/java/org/stellar/base/Memo.java#L43)) be considered to exceed 28 chars?

**Comment by jedmccaleb** [comment]
yeah it is 28 bytes long
