### ISSUE TITLE
Update xdr definitions

### ISSUE THREAD

**Issue by pieterjan84** [stellar/js-stellar-base#559]
**Is your feature request related to a problem? Please describe.**
Stellar core 19.7.0 will require pull mode. To connect to overlay with this library the xdr definitions need to be updated.

Related: Executing 'make reset-xdr' does not generate correct typescript definitions.

**Describe the solution you'd like**
Update the xdr definitions.

Thanks!

**Comment by Shaptic** [comment]
This should be complete in v9.0.0-beta.
