### ISSUE TITLE
Soroban: Support multi-party transaction signing

### ISSUE THREAD

**Issue by paulbellamy** [stellar/js-stellar-base#575]
With auth-next in soroban, transactions can require signatures for the `invokeHostFunction` arguments from multiple addresses. (In addition to the normal submission signatures).

We should figure out the workflow to support this, and add support.

One option would be to take the multiple keypairs as part of `txn.sign(keypair)`, parse through the operations, finding any where this address is the relevant signer, and signing those as well. However, this conflates the txn signer with the argument signer, which may not be true in all cases. We could add a new `txn.signContractAuth(keypair)`? Needs some design thinking.

**Comment by Shaptic** [comment]
Related: #632

**Comment by Shaptic** [comment]
Closed, at least in part, by #663
