### ISSUE TITLE
Sodium-native segmentation fault fix

### ISSUE THREAD

**Issue by zotakk4o** [stellar/js-stellar-base#583]
**Describe the bug**
The library sodium-native that you use causes segmentation fault with docker alpine images of Nodejs - https://github.com/sodium-friends/sodium-native/issues/160

In order to fix it, please upgrade the package to 4.0.0 at least.

**Comment by Shaptic** [comment]
Fixed in v9.0.0-beta as we've upgraded sodium-native.
