### ISSUE TITLE
Lexicographical sorting is not in pair with what the network expects

### ISSUE THREAD

**Issue by earrietadev** [stellar/js-stellar-base#593]
## **Describe the bug**
Back in January I got contacted by one of the users of xBull and he told me that he was not able to create a pool with two assets he's holding so I started trying it myself with the same assets and I realized that there is a mismatch between the Horizon/validators code and the JS SDK. And yesterday in the Stellar Developers discord we saw another user with the same issue but with different assets

In the JS SDK the validation of the LP assets order is done like this:
```js
    if (_asset.Asset.compare(assetA, assetB) !== -1) {
      throw new Error('Assets are not in lexicographic order');
    }
```

Which is done in the file `liquidity_pool_asset.js` with the final validation being done with: 

```js
function asciiCompare(a, b) {
  return a.localeCompare(b, 'en', { caseFirst: 'upper' });
}
```

The issue here is that with some assets combinations, the Javascript library gives a different result than the ones from the network or even with other SDKs (python for example)

## **What version are you on?**
v8.2.2

## **To Reproduce**
Here is an example written in both JS and Python (@silence48 helped me with the python part) to show the difference:

**JS**
```js
const fn = async () => {
  const loadedAccount = await server.loadAccount('GCOQDNWHUCTE5Y2II6UBJ2CBOZVU23I7YIZZHTOUMOGEPZEY3WN2FDSB');
  const sourceAccount = new SDK.Account(loadedAccount.account_id, loadedAccount.sequence);
  const assetA = new SDK.Asset('USDC', 'GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN');
  const assetB = new SDK.Asset('iDRA', 'GA7NLOF4EHWMJF6DBXXV2H6AYI7IHYWNFZR6R52BYBLY7TE5Q74AIDRA');
  const asset = new SDK.LiquidityPoolAsset(
    assetA,
    assetB,
    30,
  );

  const tx = new SDK.TransactionBuilder(loadedAccount, {
      fee: 10000000,
      networkPassphrase: 'Public Global Stellar Network ; September 2015'
    })
    .setTimeout(0)
    .addOperation(SDK.Operation.changeTrust({ asset }));
}
fn();
```

At this point the library will throw an error saying the lexicografical order is wrong, but this is not the case if we take in count that the network do expects this order (we can confirm it here: `https://horizon.stellar.org/liquidity_pools/ba986a54a2623ca07596e25aedcf688b640a6646e024b33e3fa47d1c8dceb926`)

Now unlikely to the JS version, if we do the same with python we don't face that issue:
```python
from stellar_sdk import Keypair, Network, Server, TransactionBuilder, Asset, LiquidityPoolAsset
import requests

server = Server(horizon_url="https://horizon.stellar.org")
source_account = server.load_account(account_id="GCOQDNWHUCTE5Y2II6UBJ2CBOZVU23I7YIZZHTOUMOGEPZEY3WN2FDSB")

native = Asset.native

asset_1 = Asset("USDC", "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN")
asset_2 = Asset("iDRA", "GA7NLOF4EHWMJF6DBXXV2H6AYI7IHYWNFZR6R52BYBLY7TE5Q74AIDRA")

lp = LiquidityPoolAsset(asset_1, asset_2, fee=30)

transaction = (
    TransactionBuilder(
        source_account=source_account,
        network_passphrase=Network.PUBLIC_NETWORK_PASSPHRASE,
        base_fee=100,
    )
    .set_timeout(0)
    .append_change_trust_op(lp)
)


transaction.build()
```

We confirmed this with the two pairs some users had issues: USDC/iDRA and DRIFT/DicInu

**We also want to say to possible readers:** We do not endorse any of the assets mentioned in this ticket, they were used only because users reported issues with them

## **Expected behavior**
The expected behavior is that the Stellar Base should behave in the same way the network and other stellar libraries behave.

## **Additional context**
Initial message in January: https://discord.com/channels/761985725453303838/761985800132493354/1100230956738154526

Most recent case a user faced: https://discord.com/channels/897514728459468821/905516645408182343/1100066080719900744

**Comment by silence48** [comment]
I made some tests doing the sorting here: https://runkit.com/silence48/liquidity-pool-lexical-order-issue 

From what I can tell, the https://github.com/stellar/js-stellar-base/blob/c7bcd020cb379ae8d95217246ce8c3cb86c1db9f/src/liquidity_pool_asset.js#L25 

does not do what you want.  I am assuming you want to sort the letters by ABC...XYZabc...xyz where some LETTER (say F) will always come before letter (say a) 

so if we try this, we would expect running `"F".localCompare("a", 'en', { caseFirst: 'upper' })`  would give us -1 because F is a capital letter and it's being compared to a lower case...

**However, instead we get 1.  Why?**

As best I can tell Strings localeCompare uses the Intl.Collator api when it is available... If for example, we were to sort 3 letters using this api, we can quickly see the issue:

```js
function asciiCompare(a,b, c){
 let sorted = [a,b,c].sort(new Intl.Collator('en', { caseFirst: 'upper' } ).compare);
 console.log(sorted)
 }
Compare3("i", "I", "U")
}
//returns ["I", "i", "U"]
```

Therefore according to that api, I is always before U because alphabetically I comes before U even if uppercase comes first because it sorts like this: AaBbCc...XxYyZz

I hope this has been helpful 🗡️ 

**How do we fix it?**

I'm not sure? write a manual sorting algorithm?

**Comment by silence48** [comment]
I wrote a short algorithm to sort the assets properly, but someone needs to fuzz test it first as i'm not sure i've thought of all the edge cases, possible errors.  I've put the code in a runkit located: https://runkit.com/silence48/stellar-lexic-sorting

**Comment by silence48** [comment]
I made PR #605 to fix this.  Someone should review and do some fuzz testing on it. I may still not be catching all the edge cases.
