### ISSUE TITLE
js-stellar-base: update XDR to support fees

### ISSUE THREAD

**Issue by tsachiherman** [stellar/js-stellar-base#596]
### What ? 

Update XDR to support fees

### Epic

https://github.com/stellar/soroban-tools/issues/519

**Comment by sreuland** [comment]
PR - https://github.com/stellar/js-stellar-base/pull/604

**Comment by sreuland** [comment]
found a work-around and moved https://github.com/stellar/js-stellar-base/pull/604 back to review.

**Comment by sreuland** [comment]
https://github.com/stellar/js-stellar-base/pull/604 merged
