### ISSUE TITLE
utf-8 support in MEMO_TEXT

### ISSUE THREAD

**Issue by irisli** [stellar/js-stellar-base#60]
## Overview
Although the XDR RFC only specifies that strings be ASCII many XDR libraries (like the native golang one) support utf-8. It works well since utf-8 is a superset of ASCII.

Even if there are few use cases for utf-8 in XDR strings, i think it's still important to support other languages in MEMO_TEXT.

I made a transaction containing 4 Chinese characters (12 bytes) and it comes out in multiple forms. Some of these forms are understandable since cURL outputs things differently such as the `&` but ideally, they should all show the Chinese characters

## Apparent issues:
- memo in a freshly created transaction is different from that in a transaction decoded from xdr

## Code used to reproduce this
```js
var sourceSecretKey = 'SCC2GLOCQLDIJPTQB6O2K2GVUXW52IWLSCKE76EMU5ILMED3CYQFHUFC';
var receiverPublicKey = 'GAIRISXKPLOWZBMFRPU5XRGUUX3VMA3ZEWKBM5MSNRU3CHV6P4PYZ74D';

// Calculate the source account's public key
var sourceKeypair = StellarSdk.Keypair.fromSeed(sourceSecretKey);
var sourcePublicKey = sourceKeypair.address()

// Configure StellarSdk to talk to the horizon instance hosted by Stellar.org
// To use the public (live) network, set the hostname to 'horizon.stellar.org'
var server = new StellarSdk.Server({
  hostname: 'horizon-testnet.stellar.org',
  secure: true,
  port: 443
});

server.loadAccount(sourcePublicKey)
  .then(function(account) {
    var transaction = new StellarSdk.TransactionBuilder(account)
      .addOperation(StellarSdk.Operation.payment({
        destination: receiverPublicKey,
        asset: StellarSdk.Asset.native(),
        amount: '350.1234567',
      }))
      .addMemo(StellarSdk.Memo.text('三代之時'))
      .build()

    // Sign this transaction with the secret key
    transaction.sign(sourceKeypair)

    // Let's see the XDR (encoded in base64) of the transaction we just built
    var txEnvelopeXDR = transaction.toEnvelope().toXDR('base64');
    
    console.log('Local transactionEnvelope memo just freshly created: ' + transaction.memo.value())
    console.log('Memo from Transaction built from xdr (Transaction->XDR->Transaction): ' 
      + new StellarSdk.Transaction(txEnvelopeXDR).memo.value());
    
    // Submit the transaction to the Horizon server. The Horizon server will then
    // submit the transaction into the network for us.
    server.submitTransaction(transaction)
      .then(function(result) {
        console.log('https://horizon-testnet.stellar.org' + result._links.transaction.href);
      })
      .catch(function (err){
        console.error(err);
      });
  })
```

## JS Console output
```
Local transactionEnvelope memo just freshly created: 三代之時
Memo from Transaction built from xdr (Transaction->XDR->Transaction): 	cKB
https://horizon-testnet.stellar.org/transactions/307d256a81a734e8e249b911cbe5150db3f25fdf7d9cfe6a06103ba36bcc3dbe
```

## Transaction in cURL
![image](https://cloud.githubusercontent.com/assets/5728307/11005939/c4038a54-8475-11e5-889d-fcafc3bacac4.png)

## Transaction in browser
![image](https://cloud.githubusercontent.com/assets/5728307/11005933/b6846b28-8475-11e5-9e67-99f04388fb82.png)

## Transaction in laboratory
![image](https://cloud.githubusercontent.com/assets/5728307/11006035/5457f798-8476-11e5-9265-fbb7965fb44c.png)

**Comment by bartekn** [comment]
Should be fixed after merging https://github.com/stellar/js-xdr/pull/4.
