### ISSUE TITLE
Add working example of building transaction from 0 to 1

### ISSUE THREAD

**Issue by irisli** [stellar/js-stellar-base#61]
(note: 0 means nothing. 1 means transaction created)

Right now, the docs has examples that cover the field from 0 to 1 but in order to actually go from 0 to 1, the user must combine together multiple examples. In this 0 to 1 analogy, the examples we have might look something like this: 0 to 0.6, 0.2 to 0.8, 0.4 to 1.0.

Here is an example of what I would consider building a transaction from 0 to 1. It includes signing and submission.

https://gist.github.com/irisli/71f04f472475201159e7

The example in this gist will have to be modified for js-stellar-base. Js-stellar-sdk can have a `0 to 1` that includes fetching account sequence number and transaction submission while the js-stellar-base can be a near subset (that excludes fetching seq number and submission).

**Comment by bartekn** [comment]
https://github.com/stellar/js-stellar-sdk/blob/master/docs/learn/examples.md
