### ISSUE TITLE
Add abstractions for converting `ScVal`s to native types.

### ISSUE THREAD

**Issue by Shaptic** [stellar/js-stellar-base#628]
**Is your feature request related to a problem? Please describe.**
Given an arbitrary `ScVal` type, converting it into a form natively usable from your chosen language is difficult and error prone.

**Describe the solution you'd like**
Easy conversion methods from `ScVal`s to native types.

Here is the list of types and conversations:
- [x] `scvBool` :arrow_right: `boolean`
- [x] `scvVoid` :arrow_right: `null`
- [x] `scvU32` :arrow_right: `number`
- [x] `scvI32` :arrow_right: `number`
- [x] `scvU64` :arrow_right: `bigint`
- [x] `scvI64` :arrow_right: `bigint`
- [x] `scvTimepoint` :arrow_right: `bigint`
- [x] `scvDuration` :arrow_right: `bigint`
- [x] `scvU128` :arrow_right: `bigint`
- [x] `scvI128` :arrow_right: `bigint`
- [x] `scvU256` :arrow_right: `bigint`
- [x] `scvI256` :arrow_right: `bigint`
- [x] `scvBytes` :arrow_right: `Buffer` (or should it be `Uint8Array`?)
- [x] `scvString` :arrow_right: `string`
- [x] `scvVec` :arrow_right: `Array<T>`
- [x] `scvMap` :arrow_right: `Map<ScVal, any>`, where each `ScVal` is converted to its native type if possible
- [x] `scvAddress` :arrow_right: `Address`

Some conversions are unclear and the value of an abstraction for them is a little unclear:

- [x] `scvSymbol`
- [ ] `scvContractExecutable`
- [ ] `scvLedgerKeyContractExecutable`
- [ ] `scvLedgerKeyNonce`
- [ ] `scvStatus`

**Describe alternatives you've considered**
Suffering.

**Additional context**
Original feature request from @piyalbasu here: https://github.com/stellar/js-soroban-client/issues/43.
Discord discussion here: https://discord.com/channels/897514728459468821/1111621289900253245.

**Comment by leighmcculloch** [comment]
> * ``
> * [ ]  `scvU64` ➡️ `ScInt`
> * [ ]  `scvI64` ➡️ `ScInt`
> * [ ]  `scvTimepoint` ➡️ `bigint`
> * [ ]  `scvDuration` ➡️ `bigint`
> * [ ]  `scvU128` ➡️ `ScInt`
> * [ ]  `scvI128` ➡️ `ScInt`
> * [ ]  `scvU256` ➡️ `ScInt`
> * [ ]  `scvI256` ➡️ `ScInt`

What's the win with `ScInt` for some greater than 53-bit int's when `bigint` is available?

**Comment by Shaptic** [comment]
@leighmcculloch please refer to #620: it allows easy conversion between `number|string|bigint` :left_right_arrow: `ScVal`s

**Comment by Shaptic** [comment]
Yep, you make a good point! `bigint` is a better "landing pad" for intuition, then they can use the other abstractions as needed

**Comment by willemneal** [comment]
One thing to note. Scvmap could be a rust struct, which would be better represented as a js object (TS interface). I had initially gone with `Map`, but it's a much worse DevX experience than just accessing a field.  So perhaps the conversion interface should also allow passing the corresponding ScTypeDef.

As for the bytes I vote `Uint8Array` as `Buffer` is not as cross platform.

**Comment by Shaptic** [comment]
I moved away from `Buffer` in 10a69fe1903be7d3d4c361e87ef52a228d506032, but the migration to do custom type specification definitely needs more thought and work, so I'm going to merge #630 as is to have a decent starting point.

Can you expand a bit on the API and input/output you might like to see, so I can get a better sense of what you're looking for?

**Comment by Shaptic** [comment]
I'm marking this as closed by #630 for tracking purposes, but opening a new issue for the remaining work!
