### ISSUE TITLE
possible typo in src/account.js

### ISSUE THREAD

**Issue by rahul-soshte** [stellar/js-stellar-base#629]
**Possible typo in error thrown**
In the [link](https://github.com/stellar/js-stellar-base/blob/afaacb5d2c3cc34cd555273791837a2f141ce5a3/src/account.js#L24) if you see that after passing a Muxed Account Address to isValidMed25519PublicKey(), why should the code throw an error with text "Use MuxedAccount instead"
Is the comment typo or a genuine mistake in the if conditional on line 24? Not sure.

**Comment by silence48** [comment]
I don't think it's a typo, it's saying you should [use the muxedaccount class instead]( https://github.com/stellar/js-stellar-base/blob/master/src/muxed_account.js), multiplexed addresses are like aliases for a normal account. If you read the comments at the top of the class you'll understand i think.

**Comment by rahul-soshte** [comment]
Oh damn, yeah got it. made a mistake in intrepreting.
