### ISSUE TITLE
not in sync with latest horizon: address => account_id

### ISSUE THREAD

**Issue by FredericHeem** [stellar/js-stellar-base#63]
The new horizon has changed `address` in `account_id`, however, `js-stellar-base` is still using `address`: https://github.com/stellar/js-stellar-base/blob/master/src/transaction_builder.js#L112

**Comment by bartekn** [comment]
We're in the process of changing this (the process started with this issue: https://github.com/stellar/horizon/issues/214). Will update it very soon and depreciate methods.
