### ISSUE TITLE
Improve abstractions between `ScVal`s and native types

### ISSUE THREAD

**Issue by Shaptic** [stellar/js-stellar-base#637]
While #628 makes progress on this for basic conversions (see #630 and #620), there is more to be done.

For example, 

```js
nativeToScVal("a string")
```

will always return an `ScVal.scvString`. However, it should be possible to have it return an `scvSymbol` (or even `scvBytes`, arguably). The inverse is also true, e.g. an `ScVal.scvSymbol` could be a buffer or a string. There are other irregularities as well. 

-----------

Here are some notes from @willemneal about allow type specifications for the conversions:

https://github.com/stellar/js-stellar-base/issues/628#issuecomment-1608088245:

> One thing to note. Scvmap could be a rust struct, which would be better represented as a js object (TS interface). I had initially gone with Map, but it's a much worse DevX experience than just accessing a field. So perhaps the conversion interface should also allow passing the corresponding ScTypeDef.

https://github.com/stellar/js-stellar-base/issues/628#issuecomment-1609769231:

> It would be similar to the CLI: [`soroban-spec-tools/src/lib.rs`](https://github.com/stellar/soroban-tools/blob/d16a84c2bbceccec67c3fa06a6d8f6f294a055bc/cmd/crates/soroban-spec-tools/src/lib.rs#L486)
> 
> The tricky part is figuring out the corresponding the ScTypeDef. This could be done by the bindings code. For example adding it here: [`soroban-spec-typescript/fixtures/ts/src/index.ts`](https://github.com/stellar/soroban-tools/blob/d16a84c2bbceccec67c3fa06a6d8f6f294a055bc/cmd/crates/soroban-spec-typescript/fixtures/ts/src/index.ts#L235)

-----------------

#### Acceptance Criteria

- [x] enable converting `string` to Symbol
- [x] enable converting `Buffer|Uint8Array` to String or Symbol
- [ ] attach the conversions to the `xdr.ScVal` type
- [ ] design (not necessarily implement) a way to construct objects/interfaces from a `scvMap`

**Comment by Shaptic** [comment]
@willemneal so I'm realizing that enforcing an interface type is basically impossible in this library because `stellar-base` is pure JavaScript, not TypeScript. So, really, the best we can do is return a key-value mapping as we already do here, then you can `as YourInterface` (or whatever) in your higher-level library.

The current implementation will give you a very reasonable structure, I think, as a starting point.

**Comment by willemneal** [comment]
The as casting will fail if you try to cast a map as an interface.  Eg

'''ts
interface Foo {
  a: number
}

Map<string, number> as Foo
'''

For now we can do a custom function for each user defined types. So it's doable for now if a UdT is returned but if say a map has a value type of udt. Then it becomes a JS Map.

**Comment by Shaptic** [comment]
Maybe we're talking past each other? The returned object from a `nativeToScVal` call is just a regular object, not a "`Map`" type, because this is plain JS, i.e.:

```ts
let scv = xdr.ScVal.scvMap([
  new xdr.ScMapEntry({ 
    key: xdr.ScVal.scvString("a"), 
    val: xdr.ScVal.scvU32(1) 
  })
]);
let native = scValToNative(scv); // returns { a: 1 }
let foo = native as Foo;         // works fine
```

Of course, you don't actually get proper type-checking, but that would have to be done in either generated code (like what you guys accomplished :muscle:) or somehow in soroban-client.
