### ISSUE TITLE
Add FUTURENET  networkPassphrase 

### ISSUE THREAD

**Issue by esteblock** [stellar/js-stellar-base#639]
Hello, 
I am supporting the [@soroban-react](https://github.com/esteblock/soroban-react/) library, and for the @soroban-react/chains package I would like to do

```
import * as SorobanClient from "soroban-client";
export const futurenet : WalletChain = 
  {
    id: "public",
    name: "Futurenet",
    networkPassphrase: SorobanClient.Networks.FUTURENET,
  }

```

However SorobanClient.Networks.FUTURENET does not exist here https://github.com/stellar/js-stellar-base/blob/afaacb5d2c3cc34cd555273791837a2f141ce5a3/types/index.d.ts#L220

I think it would be good to add it as Futurenet is important for Soroban development

**Comment by Shaptic** [comment]
Oh wow you're right, though it's on the `Networks` object itself in the source code lol

**Comment by Shaptic** [comment]
Wait no, this is set in the soroban branch:

https://github.com/stellar/js-stellar-base/blob/soroban/types/index.d.ts#L241-L247

I opened #654 to fix the jsdocs, though.
