### ISSUE TITLE
Add size-limit to CI to track package size

### ISSUE THREAD

**Issue by paulbellamy** [stellar/js-stellar-base#643]
Inspired by viem's usage of the [size-limit](https://www.npmjs.com/package/size-limit) js package [in their CI pipeline](https://github.com/wagmi-dev/viem/blob/main/.github/workflows/on-pull-request.yml#L42-L57) to vet new PRs, we should add something similar to make sure our bundle size gets smaller over time.

Note: We should also add issues to do the same on other js libraries.

**Comment by Shaptic** [comment]
Done in #644! This does mean the [`compressed-size-action`](https://github.com/preactjs/compressed-size-action) action requires `secrets.GITHUB_TOKEN`... Do we need a security review in that case?
