### ISSUE TITLE
Moving ed25519 to optionalDependencies

### ISSUE THREAD

**Issue by bartekn** [stellar/js-stellar-base#68]
Some users have problems with compiling [`ed25519`](https://www.npmjs.com/package/ed25519) bindings (and using our package). This package allows us to sign transactions extremely fast but for most use cases [`tweetnacl`](https://www.npmjs.com/package/tweetnacl) speed is enough and it does not require compilation.

Let's discuss if we want to move it to [`optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies).

**Comment by nullstyle** [comment]
+1.  Two notes:

1.  This should be considered a breaking change, as far as communication goes.  For those caught unaware it will significantly impact the performance of their integration.  The original motivation for including a native ed25519 module was that the wallet server wasn't able to perform well using tweetnacl.

2.  We should add a section to the README that specifically deals with the performance implications of the default configuration and also how to install the native module.
