### ISSUE TITLE
Allow users to specify transaction fee instead of base fee

### ISSUE THREAD

**Issue by irisli** [stellar/js-stellar-base#72]
In the transaction builder, it is only possible to specify a transaction fee via the option fee.

https://github.com/stellar/js-stellar-base/blob/master/src/transaction_builder.js#L67

``` js
constructor(sourceAccount, opts={}) {
  if (!sourceAccount) {
    throw new Error("must specify source account for the transaction");
  }
  this.source        = sourceAccount;
  this.operations    = [];
  this.signers       = [];

  this.baseFee    = opts.fee || BASE_FEE;
```

Then later:
https://github.com/stellar/js-stellar-base/blob/master/src/transaction_builder.js#L106

``` js
build() {
  let sequenceNumber = new BigNumber(this.source.sequenceNumber()).add(1);

  var attrs = {
    sourceAccount: Keypair.fromAccountId(this.source.accountId()).xdrAccountId(),
    fee:           this.baseFee * this.operations.length,
```

This makes it impossible to specify an exact fee. Furthermore, it is confusing because `opts.fee` becomes interpreted as what should be `opts.baseFee`.

This automatic calculation of fee was introduced here: https://github.com/stellar/js-stellar-base/commit/fa762a9926e3dca1c6b1d30f6f87df336a4ba3c2.

**Comment by bartekn** [comment]
I don't think it should be changed. `base_fee` value of the ledger is also per operation. When this value increases, you'll need to increase fee _per operation_ in your transaction. Do you have an example in which someone would need to set a fee for transaction?

> Furthermore, it is confusing because opts.fee becomes interpreted as what should be opts.baseFee.

It's documented here: https://stellar.github.io/js-stellar-sdk/TransactionBuilder.html but maybe we should change the name of this param - you're right.

**Comment by jedmccaleb** [comment]
With surge pricing you may want to set a higher fee. There may be other scenarios where you need some sort of "proof of burn" which can be dome with the fee.

**Comment by ckmakcesar** [comment]
seems working good now: 

new StellarSdk.TransactionBuilder(sourceAccount, opts={fee:765}) 
and fee<100 fails
