### ISSUE TITLE
Use "pubKey" in operationToObject

### ISSUE THREAD

**Issue by irisli** [stellar/js-stellar-base#82]
We have a deprecation warning saying:
`signer.address is deprecated. Use signer.pubKey instead.`
(https://github.com/stellar/js-stellar-base/blob/master/src/operation.js#L279)

Later, the value is still being decoded as signer.address.
(https://github.com/stellar/js-stellar-base/blob/master/src/operation.js#L535)

**Comment by irisli** [comment]
This is a breaking change. Will we announce it?

**Comment by bartekn** [comment]
It isn't a breaking change. It actually fixes a bug in `Operation.operationToObject()` method which is rarely used. We can release it as a normal release.

**Comment by bartekn** [comment]
Released: https://github.com/stellar/js-stellar-base/releases/tag/v0.5.5
