### ISSUE TITLE
Keypair.seed -> Keypair.secret

### ISSUE THREAD

**Issue by irisli** [stellar/js-stellar-base#83]
The accepted term for Stellar is "secret key".

To get the secret key from Keypair, one has to call Keypair.seed() which is confusing since we call it secret everywhere else.

https://github.com/stellar/js-stellar-base/blob/master/src/keypair.js#L37

Note: there is also Keypair.fromSeed that should be converted to something like Keypair.fromSecret

**Comment by bartekn** [comment]
Closed via https://github.com/stellar/js-stellar-base/commit/b5d05d08d360e6bbfc2fa2a945399626fe3fb321
