### ISSUE TITLE
Problem with webpack/ed25519

### ISSUE THREAD

**Issue by pakokrew** [stellar/js-stellar-base#92]
Hey,

I am developing a Webapp based on stellar, with React+Webpack, and I get some disturbing error message. The app works (using `js-stellar-sdk`), but webpack is not happy with `ed25519`dependency which requires `bindings` module, which in turns require `fs`, which is indeed not available in webpack environment.

Stacktrace : 
```
ERROR in ./~/bindings/bindings.js
Module not found: Error: Can't resolve 'fs' in '.../app/node_modules/bindings'
 @ ./~/bindings/bindings.js 6:9-22
 @ ./~/ed25519/index.js
 @ ./~/stellar-base/lib/signing.js
 @ ./~/stellar-base/lib/index.js
 @ ./~/stellar-sdk/lib/index.js
```

Maybe it is a problem with ed25519 or bindings itself, just showing the problem here. 
I see that ed25519 is requiring native modules, but I don't know much about them.

**Comment by pakokrew** [comment]
Ok I didn't understand everything, but got rid of that problem by adding this to my webpack config:
```
  plugins: [
    new webpack.ContextReplacementPlugin(/bindings$/, /^$/),
  ],
  externals: ["bindings"]
```

**Comment by bartekn** [comment]
Duplicate https://github.com/stellar/js-stellar-sdk/issues/78
