### ISSUE TITLE
Use better error message for when amount has too many digits after the decimal number

### ISSUE THREAD

**Issue by irisli** [stellar/js-stellar-base#93]
```
TypeError: amount argument must be of type String and represent a positive number or zero
    at Function.manageOffer (/Users/irisli/bookmaker/node_modules/stellar-base/lib/operation.js:407:27)
```

It's a confusing error message. Instead, it should take care of another case or just make the error message more descriptive.
```
TypeError amount argument must be of type String and have at most 7 digits after the decimal
```

Specific line (stellar-sdk is using an old version of js-stellar-base I think): https://github.com/stellar/js-stellar-base/blob/master/src/operation.js#L392

**Comment by ivjia** [comment]
still has this problem when selling
