### ISSUE TITLE
Improve Asset instanciation

### ISSUE THREAD

**Issue by pakokrew** [stellar/js-stellar-base#98]
Hey, 

> After having used the Javascript Stellar SDK for some applications, I come with my thoughts and some proposals to improve it.
> I always ended up creating helpers to use the SDK easily, and I think what my code do should be in the SDK itself.
> Some examples of my helpers : https://github.com/pakokrew/stellar-portal/blob/develop/app/js/helpers/StellarTools.js

First idea I have to propose to improve the Asset class instanciation is to create from a plain object (like for keypair).
Currently the instanciation must be `new Asset(code, issuer)`
It could also be nice to take an object as parameter with props `{asset_type, asset_code, asset_issuer}` to be generic and could be instanciated from other objects like payments, balances and so on.
For now we have to test if it type is native, call `Asset.native()` in this case, or call `new Asset(object.asset_code, object.asset_issuer)` if not.

**Comment by tomquisel** [comment]
I agree with this, although it's a minor improvement. I don't think it's worth a significant API change though. Closing it out.
