### ISSUE TITLE
Improve Classes instanciation

### ISSUE THREAD

**Issue by pakokrew** [stellar/js-stellar-base#99]
Hey, 

> After having used the Javascript Stellar SDK for some applications, I come with my thoughts and some proposals to improve it.
> I always ended up creating helpers to use the SDK easily, and I think what my code do should be in the SDK itself.
> Some examples of my helpers : https://github.com/pakokrew/stellar-portal/blob/develop/app/js/helpers/StellarTools.js

All of these classes (Asset, Keypair, ...) should come with a constructor that detects if the object passed is an instance of the class and if its the case, just return it. 
```js
const instance = new Class(previousInstance);
// If `previousInstance` is instance of `Class`, copy its data and return a new instance.
constructor(previousInstance) {
  if (previousInstance instanceof Class) {
    return previousInstance;
  }
}
```

This helps a lot when generically deserialize objects

**Comment by morleyzhi** [comment]
@pakokrew Your idea is a good one, and maybe the SDK would have been a lot better if all classes were instantiated with single objects. But we'd have to drastically change the SDK's API to conform to your new spec, and at this point I think backwards compatibility is more valuable for this package's consumers. If we're going to change the API, we'd rather produce a new package and think of this use case when designing it. But until then, I'm going to close this in the name of maintaining API consistency.
